name: Publish Docker image

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '30 2 * * *'

env:
  REGISTRY: ghcr.io
  NAME: gentoo-stage3-amd64-java

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Log in to GitHub's Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Ensure repository name is in lower case
      id: repo_name
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.actor }}
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Build image
      id: build_image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.NAME }}
        containerfiles: ./Dockerfile
    - name: Push image
      uses: redhat-actions/push-to-registry@v2
      env:
        REPO: ${{ steps.repo_name.outputs.lowercase }}
        IMAGE: ${{ steps.build_image.outputs.image }}
        TAGS: ${{ steps.build_image.outputs.tags }}
      with:
        registry: ${{ env.REGISTRY }}/${{ env.REPO }}
        image: ${{ env.IMAGE }}
        tags: ${{ env.TAGS }}
