name: Publish Docker image to GitHub's Container registry

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '0 23 * * *'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Log in to GitHub's Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.REGISTRY }}/leo3418/gentoo-stage3-amd64-openjdk:latest
