name: Publish Docker image

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '0 22 * * *'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Log in to GitHub's Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Ensure repository name is in lower case
      id: repo_name
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.actor }}
    - name: Build and push image
      uses: docker/build-push-action@v2
      env:
        REPO: ${{ steps.repo_name.outputs.lowercase }}
        NAME: gentoo-stage3-amd64-java
        TAG: latest
      with:
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.NAME }}:${{ env.TAG }}
